on:
  push:
    tags:
      - 'v*'

name: release

jobs:
  export_game:
    # Always use ubuntu-latest for this action
    runs-on: ubuntu-latest
    name: Export Game Job
    steps:
      # Always include the checkout step so that
      # your project is available for Godot to export
    - name: checkout
      uses: actions/checkout@v3
      # Ensure that you get the entire project history
      with:
        fetch-depth: 0
    # separate step to extract the version from the tag name
    - name: get tag from version
      id: tag_version
      run: |
        echo ::set-output name=TAG_VERSION::${GITHUB_REF#refs/tags/v}
    - name: install wine
      id: wine_install
      run: |
        sudo apt update
        sudo apt install wine64
        echo ::set-output name=WINE_PATH::$(which wine64)
    - name: export game
      # https://github.com/firebelley/godot-export
      uses: firebelley/godot-export@v5.2.0
      with:
        godot_executable_download_url: https://github.com/godotengine/godot/releases/download/3.4.1-stable/Godot_v3.4.1-stable_linux_headless.64.zip
        godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/3.4.1-stable/Godot_v3.4.1-stable_export_templates.tpz
        relative_project_path: ./
        create_release: true
        export_debug: false
        archive_export_output: true
        archive_single_release_output: true
        generate_release_notes: false
        base_version: ${{ steps.tag_version.outputs.TAG_VERSION }}
        # read the wine path here that was an output of the wine_install step
        wine_path: ${{ steps.wine_install.outputs.WINE_PATH }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}